export const HOST_COMMAND_IDS = [
  'app.navigate',
  'app.goBack',
  'app.goForward',
  'palette.open',
  'rail.open',
  'layout.set',
  'layout.toggle',
  'layout.toggleSidebar',
  'layout.toggleRightRail',
  'page.find',
  'conversation.new',
  'conversation.open',
  'conversation.next',
  'conversation.previous',
  'conversation.close',
  'conversation.reopenClosed',
  'conversation.togglePinned',
  'conversation.toggleArchived',
  'conversation.rename',
  'conversation.editCwd',
  'composer.focus',
  'composer.submit',
  'composer.stop',
  'composer.clear',
  'conversation.pageUp',
  'conversation.pageDown',
  'workbench.newTab',
  'workbench.closeActiveTab',
  'workbench.closeActiveFile',
  'workbench.refreshActiveFile',
  'workbench.toggleExplorer',
  'workbench.toggleDiff',
  'conversation.newAndFocus',
  'model.cycle',
  'thinking.cycle',
  'dictation.toggle',
  'sidebar.focus',
  'focus.next',
  'focus.previous',
  'selection.activate',
] as const;

export function isKnownHostCommand(command: string): boolean {
  return (HOST_COMMAND_IDS as readonly string[]).includes(command);
}
