// Generated by scripts/generate-installable-extension-catalog.mjs. Do not edit by hand.

import type { CatalogSeed } from './extensionCatalog.js';

export const INSTALLABLE_EXTENSION_CATALOG: CatalogSeed[] = [
  {
    "id": "system-agent-browser",
    "name": "Agent Browser",
    "description": "Control browsers and Electron apps with the agent-browser CLI. Docs: https://agent-browser.dev"
  },
  {
    "id": "system-alleycat",
    "name": "Kitty Litter Mobile Pairing (Alleycat)",
    "description": "Pair the Kitty Litter iOS app directly with Neon Pilot using a PA-owned Alleycat-compatible host and Codex-shaped conversation APIs."
  },
  {
    "id": "system-browser",
    "name": "Browser",
    "description": "Browse web pages beside the active conversation."
  },
  {
    "id": "system-ds4",
    "name": "DS4",
    "description": "DeepSeek V4 Flash local model profile and ds4-agent-shaped tools for antirez/ds4."
  },
  {
    "id": "system-duckduckgo-search",
    "name": "DuckDuckGo Search",
    "description": "Agent web search tool backed by DuckDuckGo HTML results."
  },
  {
    "id": "system-exa-search",
    "name": "Exa Search",
    "description": "Agent tool for Exa web search."
  },
  {
    "id": "system-local-models",
    "name": "Local Models",
    "description": "Manage local MLX and GGUF model runtimes from one workspace."
  },
  {
    "id": "system-onboarding",
    "name": "Onboarding",
    "description": "Creates a one-time onboarding conversation for new Neon Pilot installs."
  },
  {
    "id": "system-self-preservation",
    "name": "Self Preservation",
    "description": "Blocks the agent from killing its own process."
  },
  {
    "id": "system-suggested-context",
    "name": "Suggested Context",
    "description": "Suggests related conversations as pointer context for new prompts."
  },
  {
    "id": "system-video-probe",
    "name": "Video Probe",
    "description": "Analyze video files using a video-capable model. Manages a local mlx-vlm runtime (Apple Silicon) or routes to OpenRouter."
  }
];

