import { dirname, join } from 'node:path';

import { AuthStorage, ModelRegistry } from '@earendil-works/pi-coding-agent';
import { getPiAgentRuntimeDir } from '@neon-pilot/core';

import { resolveIndexedProviderApiKey, resolveProviderApiKey } from '../secrets/secretStore.js';
import { normalizeModelContextWindow } from './modelContextWindows.js';

type RegistryModel = ReturnType<ModelRegistry['getAvailable']>[number];

function shouldHideNeonPilotModel(model: RegistryModel): boolean {
  // The opencode-go Kimi 2.6 gateway rejects the reasoning payloads generated by
  // the current pi-ai provider. Hide it until the provider contract is corrected.
  return model.provider === 'opencode-go' && model.id === 'kimi-k2.6';
}

function applyNeonPilotModelMetadataOverrides(model: RegistryModel): RegistryModel {
  const contextWindow = normalizeModelContextWindow(model.id, model.contextWindow, 128_000);

  if (contextWindow !== model.contextWindow) {
    return { ...model, contextWindow };
  }

  return model;
}

function sanitizeProviderAuthError(provider: string, error: string): string {
  if (/Failed to resolve API key for provider/i.test(error) || /find-generic-password/i.test(error)) {
    return `No API key is available for provider "${provider}". Add one in Settings, then try again.`;
  }

  return error;
}

function applyNeonPilotRegistryOverrides(registry: ModelRegistry): ModelRegistry {
  const originalGetAll = registry.getAll.bind(registry);
  const originalGetAvailable = registry.getAvailable.bind(registry);
  const originalFind = registry.find.bind(registry);
  const originalGetApiKeyAndHeaders = registry.getApiKeyAndHeaders.bind(registry);
  const modelKey = (model: RegistryModel) => `${model.provider}\0${model.id}`;

  registry.getAll = () =>
    originalGetAll()
      .filter((model) => !shouldHideNeonPilotModel(model))
      .map(applyNeonPilotModelMetadataOverrides);
  registry.getAvailable = () => {
    const piAvailableModels = new Set(originalGetAvailable().map(modelKey));
    return originalGetAll()
      .filter((model) => piAvailableModels.has(modelKey(model)) || Boolean(resolveIndexedProviderApiKey(model.provider)))
      .filter((model) => !shouldHideNeonPilotModel(model))
      .map(applyNeonPilotModelMetadataOverrides);
  };
  registry.find = (provider: string, modelId: string) => {
    const model = originalFind(provider, modelId);
    if (model && shouldHideNeonPilotModel(model)) {
      return undefined;
    }
    return model ? applyNeonPilotModelMetadataOverrides(model) : undefined;
  };
  registry.getApiKeyAndHeaders = async (model) => {
    const result = await originalGetApiKeyAndHeaders(model);
    const apiKey = resolveProviderApiKey(model.provider);
    if (result.ok === false) {
      result.error = sanitizeProviderAuthError(model.provider, result.error);
    }
    if (!apiKey) return result;
    return result.ok ? { ...result, apiKey } : { ok: true, apiKey };
  };

  return registry;
}

export function createRuntimeModelRegistry(authStorage: AuthStorage): ModelRegistry {
  return applyNeonPilotRegistryOverrides(ModelRegistry.create(authStorage, join(getPiAgentRuntimeDir(), 'models.json')));
}

export function createModelRegistryForAuthFile(authFile: string): ModelRegistry {
  const authStorage = AuthStorage.create(authFile);
  return applyNeonPilotRegistryOverrides(ModelRegistry.create(authStorage, join(dirname(authFile), 'models.json')));
}
