export type { ActivityTreeItem } from '../activity/activityTree';
export { type ActivityTreeDropPosition, ActivityTreeView, type ActivityTreeViewProps } from '../activity/ActivityTreeView';
export { buildDesktopWebSocketUrl } from '../client/endpoints';
export { buildApiPath } from '../client/apiBase';
export { ChatRailComposer, type ChatRailComposerProps } from '../components/chat/ChatRailComposer';
export { ChatView, type ChatViewProps } from '../components/chat/ChatView';
export type { ChatViewLayout } from '../components/chat/chatViewTypes';
export { CheckpointInlineDiff } from '../components/chat/CheckpointInlineDiff';
export { DiffActionButton, GitDiffIcon } from '../components/chat/DiffActionButton';
export { ContextMenuWrapper } from '../components/shared/ContextMenuWrapper';
export { canDropAllPaths, getTopLevelDraggedPaths, useFileTreeModel } from '../components/shared/useFileTreeModel';
export {
  AppPageEmptyState,
  AppPageIntro,
  AppPageLayout,
  AppPageSection,
  AppPageToc,
  AttachmentChip,
  AttachmentChipButton,
  type AttachmentChipSize,
  BrowsePathButton,
  Button,
  ButtonLink,
  CardBody,
  CardMeta,
  CardTitle,
  CenteredLoadingState,
  CenteredMessage,
  CenteredState,
  ChatBubbleIcon,
  Checkbox,
  CheckButton,
  ChoiceRow,
  CodeBlock,
  CompactCard,
  type CompactCardPadding,
  type CompactCardTone,
  ComposerActionButton,
  type ComposerActionButtonSize,
  type ComposerActionButtonTone,
  ConfirmDialog,
  type ConfirmDialogProps,
  cx,
  DashboardGrid,
  DashboardGridCell,
  type DashboardGridColumns,
  type DashboardGridDivide,
  DataTable,
  DataTableActionGroup,
  DataTableBody,
  DataTableCell,
  DataTableEmptyRow,
  DataTableHead,
  DataTableHeaderCell,
  DataTableRow,
  Dialog,
  DialogBody,
  DialogFooter,
  DialogHeader,
  Disclosure,
  EditorToolbar,
  EditorToolbarButton,
  EditorToolbarGroup,
  EmptyState,
  ErrorState,
  Field,
  FieldError,
  FieldHint,
  FieldLabel,
  FilterToolbar,
  FolderIcon,
  FolderPlusIcon,
  formatKeyboardShortcutLabel,
  IconButton,
  type IconButtonShape,
  type IconButtonSize,
  IconLink,
  InlineCode,
  InlineCodeButton,
  InlineMeta,
  InlineSelect,
  InlineTextInput,
  KeyboardShortcutCaptureInput,
  KeyValueItem,
  KeyValueList,
  KeyValueTable,
  type KeyValueTableColumns,
  LoadingState,
  MenuGroupLabel,
  MenuItem,
  MenuSeparator,
  MenuShell,
  MessageActionButton,
  MessageCard,
  type MessageCardRole,
  MessageMeta,
  MetaLabel,
  MetricTile,
  type MetricTone,
  Notice,
  PanelHeader,
  PanelMessage,
  Pill,
  PositionedMenu,
  ProgressBar,
  ProgressRow,
  RailSection,
  RailSubsection,
  ResourceList,
  ResourceListItem,
  ResourceListLink,
  ResourceListRow,
  ResourcePickerDialog,
  ResourcePickerList,
  ResourcePickerToolbar,
  RingStatusDot,
  RowButton,
  RuntimeFooter,
  RuntimeHeader,
  RuntimeHeaderControls,
  RuntimePage,
  RuntimeSection,
  RuntimeStatusDot,
  type RuntimeStatusTone,
  RuntimeStrip,
  SearchInput,
  SectionLabel,
  type SectionLabelTone,
  SegmentedControl,
  Select,
  SettingsPanel,
  SettingsRow,
  SettingsSection,
  SettingToggleRow,
  ShelfBody,
  ShelfHeader,
  ShelfSection,
  SidebarActionHeader,
  SidebarList,
  SidebarMessage,
  SidebarNavButton,
  SidebarRow,
  SidebarSection,
  SidebarTemplateList,
  Spinner,
  Stat,
  StatGrid,
  StatusDot,
  SupportingText,
  SurfacePanel,
  SwatchOption,
  Switch,
  TabButton,
  TabList,
  TabPanel,
  TaskListItem,
  TerminalBlock,
  Textarea,
  TextButton,
  TextInput,
  TextLink,
  TextPromptDialog,
  type TextPromptDialogProps,
  ToolbarButton,
  ToolResultCard,
  type ToolResultCardTone,
  Tooltip,
  WorkbenchHeader,
  WorkbenchShell,
} from '../components/ui';
export { Keycap } from '../components/ui';
export { type DesktopKnowledgeEntryContextMenuAction, getDesktopBridge, shouldUseNativeAppContextMenus } from '../desktop/desktopBridge';
export { createDesktopAwareEventSource } from '../desktop/desktopEventSource';
export { useApi } from '../hooks/useApi';
export { useInvalidateOnTopics } from '../hooks/useInvalidateOnTopics';
export {
  addOpenFileId,
  KNOWLEDGE_OPEN_FILE_IDS_STORAGE_KEY,
  normalizeOpenFileIds,
  readStoredOpenFileIds,
  removeOpenFileId,
  renameOpenFileIds,
  writeStoredOpenFileIds,
} from '../local/knowledgeOpenFiles';
export {
  readStoredRecentlyClosedFileIds,
  recordRecentlyClosedFileId,
  writeStoredRecentlyClosedFileIds,
} from '../local/knowledgeRecentlyClosedFiles';
export {
  collapseExpandedFolderIds,
  KNOWLEDGE_TREE_EXPANDED_FOLDERS_STORAGE_KEY,
  readStoredExpandedFolderIds,
  renameExpandedFolderIds,
  writeStoredExpandedFolderIds,
} from '../local/knowledgeTreeState';
export { lazyRouteWithRecovery } from '../navigation/lazyRouteRecovery';
export { type ExtensionChatContextMessage, ExtensionChatRail, type ExtensionChatRailProps } from './ExtensionChatRail';
export { streamExtensionRouteSse } from './extensionRouteStream';
export { type ExtensionSettingsPanelRegistration, SettingsPanelHost } from './SettingsPanelHost';
export { SidebarTreeSection, type SidebarTreeSectionProps } from './SidebarTreeSection';
export type { ExtensionSurfaceProps } from './types';
