export type AskUserQuestionAnswers = unknown;
export type AskUserQuestionPresentation = unknown;
export type AppTelemetryEventRow = unknown;
export type AutoModeSummary = unknown;
export type CacheEfficiencyAggregate = unknown;
export type ContextPointerUsageResult = unknown;
export type ExtensionInstallSummary = unknown;
export type KnowledgeBaseState = unknown;
export type KnowledgeBacklink = unknown;
export type KnowledgeBacklinksResult = unknown;
export type KnowledgeEntry = unknown;
export type KnowledgeFileContent = unknown;
export type KnowledgeFileListResult = unknown;
export type KnowledgeFileSummary = unknown;
export type KnowledgeImageUploadResult = unknown;
export type KnowledgeSearchResponse = unknown;
export type KnowledgeShareImportResult = unknown;
export type KnowledgeTreeResult = unknown;
export type MemoryDocItem = unknown;
export type MentionItem = unknown;
export type RelatedConversationSearchResult = unknown;
export type ScheduledTaskSchedulerHealth = unknown;
export type ScheduledTaskSummary = unknown;
export type SessionMeta = unknown;
export type SystemPromptAggregate = unknown;
export type ToolFlowResult = unknown;
export type TraceAgentLoop = unknown;
export type TraceCompactionAggs = unknown;
export type TraceCompactionEvent = unknown;
export type TraceContextSession = unknown;
export type TraceModelUsage = unknown;
export type TraceThroughput = unknown;
export type TraceTokenDaily = unknown;
export type TraceToolHealth = unknown;

export declare const CONVERSATION_LAYOUT_CHANGED_EVENT: string;
export declare const api: unknown;
export declare function useAppData(...args: never[]): unknown;
export declare function notifyExtensionRegistryChanged(...args: never[]): void;
export declare function readConversationLayout(...args: never[]): unknown;
export declare function timeAgo(...args: never[]): string;
export declare function timeAgoCompact(...args: never[]): string;
export declare function summarizeConversationCwd(...args: never[]): string;
