import type { ExtensionDesktopBridge } from './desktopBridge.js';

export type HostComponent = (...args: never[]) => unknown;
export type AppTelemetryLogBundleExport = unknown;
export type AppTelemetryLogDiagnostics = unknown;
export type DesktopAppPreferencesState = unknown;
export type DesktopEnvironmentState = unknown;
export type ModelEditorDraft = unknown;
export interface JsonObjectDraftEntry {
  key: string;
  valueText: string;
}
export type ModelProviderApi = unknown;
export type ModelProviderConfig = unknown;
export type ModelProviderModelConfig = unknown;
export type ModelProviderState = unknown;
export type ModelState = unknown;
export type ProviderAuthSummary = unknown;
export type ProviderEditorDraft = unknown;
export type ProviderOAuthLoginState = unknown;
export type ProviderOAuthLoginStreamEvent = unknown;
export type TelemetryDbMaintenanceResult = unknown;
export interface ColorTheme {
  id: string;
  label: string;
  appearance: 'light' | 'dark';
  tokens?: Record<string, string>;
  extensionId?: string;
}
export type ThemePreference = 'light' | 'dark' | 'system';
export type ThemeAccent = 'lime' | 'forest' | 'cobalt' | 'ember' | 'violet' | 'ink';
export type TranscriptionModelStatus = unknown;
export type TranscriptionProviderId = unknown;
export type UnifiedSettingsEntry = unknown;

export declare const DesktopConnectionsSettingsPanel: HostComponent; // App behavior panel
export declare const DesktopKeyboardShortcutsSettingsSection: HostComponent;
export declare const SettingsPage: HostComponent;
export declare const SettingsPanel: HostComponent;
export declare const SettingsRow: HostComponent;
export declare const SettingsSection: HostComponent;
export declare const SettingToggleRow: HostComponent;
export declare const SettingsField: HostComponent;
export declare const AppPageIntro: HostComponent;
export declare const AppPageLayout: HostComponent;
export declare const AppPageSection: HostComponent;
export declare const AppPageToc: HostComponent;
export declare const Button: HostComponent;
export declare const Checkbox: HostComponent;
export declare const ErrorState: HostComponent;
export declare const Field: HostComponent;
export declare const FieldError: HostComponent;
export declare const FieldHint: HostComponent;
export declare const FieldLabel: HostComponent;
export declare const LoadingState: HostComponent;
export declare const Notice: HostComponent;
export declare const PanelMessage: HostComponent;
export declare const Pill: HostComponent;
export declare const Disclosure: HostComponent;
export declare const ProgressBar: HostComponent;
export declare const RailSubsection: HostComponent;
export declare const Select: HostComponent;
export declare const SegmentedControl: HostComponent;
export declare const SupportingText: HostComponent;
export declare const Switch: HostComponent;
export declare const Textarea: HostComponent;
export declare const TextInput: HostComponent;
export declare const THINKING_LEVEL_OPTIONS: unknown;
export declare const CORE_KEYBOARD_SHORTCUT_REGISTRATIONS: ReadonlyArray<{
  id: string;
  title: string;
  description: string;
  command: string;
  defaultKeys: string[];
  menu: 'file' | 'edit' | 'view' | 'app';
}>;
export declare const DEFAULT_DESKTOP_KEYBOARD_SHORTCUTS: Record<string, string>;
export declare const ToolbarButton: HostComponent;
export declare const Tooltip: HostComponent;
export declare const api: unknown;
export declare function cx(...values: Array<unknown>): string;
export declare function createDesktopAwareEventSource(...args: never[]): unknown;
export declare function createModelEditorDraft(...args: never[]): unknown;
export declare function createProviderEditorDraft(...args: never[]): unknown;
export declare function formatContextWindowLabel(...args: never[]): unknown;
export declare function formatThinkingLevelLabel(...args: never[]): unknown;
export declare function getDesktopBridge(...args: never[]): ExtensionDesktopBridge | null;
export declare function getModelSelectableServiceTierOptions(...args: never[]): unknown;
export declare function groupModelsByProvider(...args: never[]): unknown;
export declare function isDesktopShell(...args: never[]): unknown;
export declare function parseOptionalJsonObject(...args: never[]): unknown;
export declare function parseOptionalNonNegativeNumber(...args: never[]): unknown;
export declare function parseOptionalPositiveInteger(...args: never[]): unknown;
export declare function parseOptionalStringRecord(...args: never[]): unknown;
export declare function readJsonObjectDraftEntries(text: string, label: string): JsonObjectDraftEntry[];
export declare function writeJsonObjectDraftEntries(entries: JsonObjectDraftEntry[]): string;
export declare function writeStringRecordDraftEntries(entries: JsonObjectDraftEntry[]): string;
export declare function readDesktopEnvironment(...args: never[]): unknown;
export declare function resetStoredConversationUiState(...args: never[]): unknown;
export declare function resetStoredLayoutPreferences(...args: never[]): unknown;
export declare function subscribeDesktopProviderOAuthLogin(...args: never[]): unknown;
export declare function useApi(...args: never[]): unknown;
export declare function useInvalidateOnTopics(...args: never[]): unknown;
export declare function useTheme(): {
  theme: string;
  themePreference: ThemePreference;
  lightTheme: string;
  darkTheme: string;
  availableThemes: ColorTheme[];
  accent: ThemeAccent;
  availableAccents: Array<{
    id: ThemeAccent;
    label: string;
    light: { accent: string; accentBg: string; selection: string; warning: string };
    dark: { accent: string; accentBg: string; selection: string; warning: string };
  }>;
  setThemePreference: (theme: ThemePreference) => void;
  setLightTheme: (theme: string) => void;
  setDarkTheme: (theme: string) => void;
  setAccent: (accent: ThemeAccent) => void;
  toggle: () => void;
};
