import type { ExtensionDesktopBridge } from './desktopBridge.js';
import type { BrowserTabItem, BrowserTabsState } from './workbenchBrowserTabs.js';

export type HostComponent = (...args: never[]) => unknown;
export type { BrowserTabItem, BrowserTabsState };

export declare const TerminalToolBlock: HostComponent;
export declare const ConversationArtifactRailContent: HostComponent;
export declare const ConversationArtifactWorkbenchPane: HostComponent;
export declare const ConversationCheckpointWorkbenchPane: HostComponent;
export declare const ConversationDiffRailContent: HostComponent;
export declare const WorkbenchBrowserTab: HostComponent;
export declare const WorkspaceExplorer: HostComponent;
export declare const WorkspaceFileDocument: HostComponent;
export declare function getConversationCheckpointIdFromSearch(search: string): string | null;
export declare function setConversationCheckpointIdInSearch(search: string, checkpointId: string | null): string;
export declare function readArtifactPresentation(...args: never[]): unknown;
export declare function readCheckpointPresentation(...args: never[]): unknown;
export declare function readAskUserQuestionPresentation(...args: never[]): unknown;
export declare function describeAskUserQuestionState(...args: never[]): unknown;
export declare function readTerminalBashToolPresentation(...args: never[]): unknown;
export declare function setConversationArtifactIdInSearch(search: string, artifactId: string | null): string;
export declare function getConversationRunIdFromSearch(search: string): string | null;
export declare function setConversationRunIdInSearch(search: string, runId: string | null): string;
export declare function useConversationArtifactSummaries(...args: never[]): unknown;
export declare function useConversationCheckpointSummaries(...args: never[]): unknown;
export declare function getDesktopBridge(...args: never[]): ExtensionDesktopBridge | null;
export declare function cx(...values: Array<unknown>): string;
export declare function createNewTab(): BrowserTabItem;
export declare function getAdjacentTabId(state: BrowserTabsState, closedTabId: string): string | null;
export declare function getTabSessionKey(tabId: string): string;
export declare function readBrowserTabsState(): BrowserTabsState;
export declare function writeBrowserTabsState(state: BrowserTabsState): void;
